sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t nayu1105/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true nayu1105/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react-app'
  env: 'Docker-react-app-env'
  bucket_name: 'elasticbeanstalk-us-east-1-845142907605'
  bucket_path: 'docker-react-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrey_access_key: $AWS_SECRET_ACCESS_KEY
